In [1]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

import numpy as np

null_vec = np.zeros(10)
null_vec[4] = 1

print(null_vector)



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
vec = np.arange(10, 50)
print(vec)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

arr= np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)


(array([0, 1, 4], dtype=int64),)


In [7]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np
arr = np.random.rand(10, 10)
min_val = np.min(arr)
max_val = np.max(arr)

print("Minimum value:", min_val)
print("Maximum value:", max_val)


Minimum value: 0.0035995657003328185
Maximum value: 0.9934243375098877


In [8]:
# 6. Create a random vector of size 30 and find the mean value.
import numpy as np
vec = np.random.rand(30)
mean_val = np.mean(vec)
print("Mean value:", mean_val)


Mean value: 0.4899730627016702
